### ISSUE TITLE
Hi, just a review from the point of my own personal experience/preference

### ISSUE THREAD

**Issue by Challanger524** [braxtons12/hyperion_mpl#5]
Hi 👋,

#### 1. header files extension
Why not to use `*.hpp` for `C++` files, especially when utilizing cpp-only feature - **templates** !?

#### 2. include guards
Why would anybody use C-style header guards in C++20 in the year 2024???

#### 3. horizontal indentation inside namespaces
``` c++
namespace hyperion::mpl {

    template<typename... TTypes>
    struct List;
    ...
} // namespace hyperion::mpl
```
- harms readability (by permanent odd indentation)

#### 4. tests
``` c++
namespace hyperion::mpl::_test::list {
```
1703 - 1396 = 307 lines for tests, that can be moved to `mpl/tests/test_list.hpp` and just be included at the end of `mpl/list.hpp` (if needed) to **declutter** things

#### 5. `README.md#example`
- Would be nice to separate different tests with comment-headers like: `// testing <things>`
- Also feel lack of closer to real usage examples that will show what this library is aiming to simplify/achieve
  - maybe there will appear some with time

## Happy to see
- `CMakePresets.json`
- `CMakeLists.txt`
  - not crucial, but `file(GLOB_RECURSE` can be used to gather all sources
  - and `list(FILTER _SOURCE_FILES EXCLUDE REGEX ".*\\/_.*\\..*")` to exclude `_<temp_file>`

**Comment by mguid65** [comment]
Hello, some feedback for your feedback:
 
### 1. Include Guards
Even though  `#pragma once` is supported on major compilers, it is still non-standard. For some people this may not matter, especially on a compiler that supports C++20 which almost certainly supports this pragma. 

I am aware that preprocessor guards are slower than `#pragma once`


### 2. Glob Recurse

CMake recommends not using GLOB for this type of thing:

"We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate. The CONFIGURE_DEPENDS flag may not work reliably on all generators, or if a new generator is added in the future that cannot support it, projects using it will be stuck. Even if CONFIGURE_DEPENDS works reliably, there is still a cost to perform the check on every rebuild."

**Comment by braxtons12** [comment]
Hi, some general responses.

### 1. header files extension

Frankly I don't see the point in the bike-shedding over file extension. There's no standard-ordained extension, and it's clearly a C++ library.

### 2. include guards

As @mguid65 pointed out, `#pragma once` is non-standard. While any compiler I would expect this library to work with also supports `#pragma once`, I'd prefer to stick to standard-compliant features.
In addition to that, several headers in the library are co-dependent, and in such scenarios `#pragma once` can't be used reliably.

### 3. horizontal indentation inside namespaces

This is my personal style and I would argue that in the general case it _helps_ readability. The indentation makes it easier to visually track/grep what namespace any individual item is in.

### 4. tests

The purpose of the tests being directly in the header is:
- immediately verifies correctness of the code upon inclusion.
- provides a quick list of _basic_ examples for users directly with the code in question
 
moving to a separate header eliminates both of those.

### 5. README.md#example

I agree the examples section code use some improvement. It's hard to come up w/ an example that is trivial enough to be reasonable for a README while also being complicated enough to demonstrate the usage and advantages of the library. (I would rather not implement `variant` in my README, for example, haha) If you have any suggestions here, please feel free!

**Comment by Challanger524** [comment]
1. `*.h` is clearly a C header, with no relation to modern C++
2. `#pragma once` is a standard de-facto, [all](https://en.wikipedia.org/wiki/Pragma_once#Portability) known compilers implements it and guessing about possibility to encounter a modern compiler "that don't" - is genuinely ridiculous
   - no argue about usage of `ifdef-guards` where it is required by logic
3. yep, rather a matter of taste
4. 👍 
5. what cames to my mind first - is using `type_traits` to enable template function for arithmetic parameters only
